# GitHub Actions Workflow with MATLAB Actions
#
# For a general overview of GitHub Actions, see
# https://docs.github.com/en/actions
#
# For using MathWorks products in GitHub Actions, see
# https://github.com/matlab-actions/overview
#
# For details about the syntax of this file, see
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# Copyright 2021-2023 The MathWorks, Inc.

name: CI using MATLAB

on:
  push:
    branches: [ R2023a ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

  pull_request:
    branches: [ R2023a ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

jobs:

  job-check-project:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); BEVProject_CheckProject_runtests;

  job-run-tests:

    # This job starts only if the previous job is successful.
    needs: job-check-project

    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023a

      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); BEVProject_runtests;
